/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.QLNVDAO;
import entity.QLNVENTITY;
import utils.Global;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author thanh
 */
public class LoginJFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginJFrame
     */
    public LoginJFrame() {
        initComponents();
        setLocationRelativeTo(null);
        xuLyDangNhap();
    }
    
    public void xuLyDangNhap(){
        hienThiMatKhauCheckBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (hienThiMatKhauCheckBox.isSelected()) {
                    txtMATKHAU.setEchoChar((char) 0);  // Hiển thị mật khẩu
                } else {
                    txtMATKHAU.setEchoChar('*');  // Ẩn mật khẩu
                }
            }
        });
    }
    
    public void xuLyNutDangNhap(){
        btnDANGNHAP.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String username = txtUSERNAME.getText().trim();
                String password = new String(txtMATKHAU.getPassword()).trim();

                // Kiểm tra thông tin đăng nhập
                if (isValidInput(username, password)) {
                    // Kiểm tra tài khoản và mật khẩu
                    QLNVDAO dao = new QLNVDAO();
                    QLNVENTITY user = dao.getUserByEmailOrPhone(username);
                    if (user != null && password.equals(user.getMatKhau())) {
                        // Chuyển đến trang chính theo quyền
                        Global.setSession(user, password);
                        openHomePage(user.getQuyen());
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Sai thông tin đăng nhập!");
                    }
                }
            }
        });
    }
    
    private boolean isValidInput(String username, String password) {
        // Kiểm tra cú pháp email
        if (username.contains("@")) {
            Pattern emailPattern = Pattern.compile("^[A-Za-z0-9+_.-]+@(.+)$");
            Matcher emailMatcher = emailPattern.matcher(username);
            if (!emailMatcher.matches()) {
                JOptionPane.showConfirmDialog(rootPane, "Email không hợp lệ!");
                return false;
            }
        }
        // Kiểm tra cú pháp số điện thoại
        else {
            if (username.length() < 10 || username.length() > 11 || !username.startsWith("0")) {
                JOptionPane.showMessageDialog(rootPane, "Số điện thoại không hợp lệ!");
                return false;
            }
        }

        // Kiểm tra mật khẩu
        if (password.isEmpty() || password.equals("Mật Khẩu")) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập mật khẩu!");
            return false;
        }

        return true;
    }

    // Mở trang Home tùy theo quyền
    private void openHomePage(int quyen) {
        if (quyen == 1) {
            HomeJFrame homeJFrame = new HomeJFrame(1);
            homeJFrame.setVisible(true);
            this.dispose();
            JOptionPane.showMessageDialog(rootPane, "Đăng nhập thành công với tư cách là Admin!");
        } else if (quyen == 2) {
            HomeJFrame homeJFrame = new HomeJFrame(10);
            homeJFrame.setVisible(true);
            this.dispose();
            JOptionPane.showMessageDialog(rootPane, "Đăng nhập thành công với tư cách là Nhân Viên!");
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        txtUSERNAME = new javax.swing.JTextField();
        btnDANGNHAP = new javax.swing.JButton();
        btnTHOAT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        hienThiMatKhauCheckBox = new javax.swing.JCheckBox();
        txtMATKHAU = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtUSERNAME.setText("0904967551");

        btnDANGNHAP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/Accept.png"))); // NOI18N
        btnDANGNHAP.setText("Đăng Nhập");
        btnDANGNHAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDANGNHAPActionPerformed(evt);
            }
        });

        btnTHOAT.setText("Thoát");
        btnTHOAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTHOATActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Đăng Nhập Vào Quản Lý Bán Đồ Công Nghệ");

        hienThiMatKhauCheckBox.setText("Hiển Thị Mật Khẩu");

        txtMATKHAU.setText("123123");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel2.setText("Email/Số Điện Thoại");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel3.setText("Mật Khẩu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUSERNAME)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMATKHAU))
                        .addContainerGap(72, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDANGNHAP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTHOAT))
                            .addComponent(hienThiMatKhauCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addComponent(txtUSERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(txtMATKHAU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(hienThiMatKhauCheckBox)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDANGNHAP)
                            .addComponent(btnTHOAT)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDANGNHAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDANGNHAPActionPerformed
        // TODO add your handling code here:
        xuLyNutDangNhap();
    }//GEN-LAST:event_btnDANGNHAPActionPerformed

    private void btnTHOATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTHOATActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnTHOATActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDANGNHAP;
    private javax.swing.JButton btnTHOAT;
    private javax.swing.JCheckBox hienThiMatKhauCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPasswordField txtMATKHAU;
    private javax.swing.JTextField txtUSERNAME;
    // End of variables declaration//GEN-END:variables
}
