/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.util.*;
import dao.QLSPDAO;
import entity.QLSPENTITY;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSI USER
 */
public class QuanLySanPhamJPanel extends javax.swing.JPanel {

    private int rowSP = -1;
    private QLSPDAO spdao = new QLSPDAO();
    private Map<String, Integer> thmap;
    private Map<String, Integer> dmmap;
    private Map<String, Integer> ttmap = new HashMap();
    private String getKeyFromValue(Map<String, Integer> map, int value){
        for (Map.Entry<String, Integer> entry : map.entrySet()) {
            if(entry.getValue() == value){
                return entry.getKey();
            }
        }
        return null;
    }
    /**
     * Creates new form QuanLySanPhamJPanel
     */
    public QuanLySanPhamJPanel() {
        initComponents();
        fillCBTH();
        fillCBDM();
        fillCBTT();
        fillTB();
    }
    
    public void fillCBTH(){
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        thmap = spdao.getTH();
        for (Map.Entry<String, Integer> entry : thmap.entrySet()) {
            model.addElement(entry.getKey());
        }
        cbTENTH.setModel(model);
    }
    
    public void fillCBDM(){
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        dmmap = spdao.getDM();
        for (Map.Entry<String, Integer> entry : dmmap.entrySet()) {
            model.addElement(entry.getKey());
        }
        cbTENDM.setModel(model);
    }
    
    public void fillCBTT(){
        ttmap.put("Active", 1);
        ttmap.put("Inactive", 2);
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (Map.Entry<String, Integer> entry : ttmap.entrySet()) {
            model.addElement(entry.getKey());
        }
        cbTRANGTHAI.setModel(model);
    }
    
    public void fillTB(){
        DefaultTableModel model = (DefaultTableModel) tblSANPHAM.getModel();
        model.setRowCount(0);
        for (QLSPENTITY sp : spdao.getAllSP()) {
            String tenDM = getKeyFromValue(dmmap, sp.getMaDM());
            String tenTH = getKeyFromValue(thmap, sp.getMaTH());
            String tenTT = getKeyFromValue(ttmap, sp.getTrangThaiSP());
            Object data[] = {
                sp.getMaSP(),
                tenDM,
                tenTH,
                sp.getTenSP(),
                sp.getGiaSP(),
                sp.getSoLuongSP(),
                tenTT,
                sp.getMoTa()
            };
            model.addRow(data);
        }
        tblSANPHAM.setModel(model);
    }
    
    public QLSPENTITY getSP(){
        String tenDM = (String) cbTENDM.getSelectedItem();
        String tenTH = (String) cbTENTH.getSelectedItem();
        String tenSP = txtTENSP.getText();
        float giaSP = Float.parseFloat(txtGIA.getText());
        int soLuongSP = Integer.parseInt(txtSOLUONG.getText());
        String trangThaiSP = (String) cbTRANGTHAI.getSelectedItem();
        String moTa = txtMOTA.getText().isBlank() ? "Không có mô tả cho sản phẩm này" : txtMOTA.getText();
        int maDM = dmmap.get(tenDM);
        int maTH = thmap.get(tenTH);
        int maTT = ttmap.get(trangThaiSP);
        int maSP = 0;
        if(!txtMASP.getText().isBlank()){
            maSP = Integer.parseInt(txtMASP.getText());
        }
        QLSPENTITY sp = new QLSPENTITY(maSP, maDM, maTH, soLuongSP, maTT, giaSP, tenSP, moTa);
        return sp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSANPHAM = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMASP = new javax.swing.JTextField();
        txtTENSP = new javax.swing.JTextField();
        cbTRANGTHAI = new javax.swing.JComboBox<>();
        txtMOTA = new javax.swing.JTextField();
        txtSOLUONG = new javax.swing.JTextField();
        txtGIA = new javax.swing.JTextField();
        btnXOA = new javax.swing.JButton();
        btnSUA = new javax.swing.JButton();
        btnTHEM = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cbTENDM = new javax.swing.JComboBox<>();
        cbTENTH = new javax.swing.JComboBox<>();
        btnDANHMUC = new javax.swing.JButton();
        btnTHUONGHIEU = new javax.swing.JButton();

        tblSANPHAM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Sản Phẩm", "Tên Danh Mục", "Tên Thương Hiệu", "Tên Sản Phẩm", "GIá", "Số Lượng", "Trạng Thái", "Mô Tả"
            }
        ));
        tblSANPHAM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSANPHAMMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSANPHAM);

        jLabel1.setText("Mã Sản Phẩm");

        jLabel2.setText("Tên Thương Hiệu");

        jLabel3.setText("Tên Sản Phẩm");

        jLabel4.setText("Giá");

        jLabel5.setText("Số Lượng");

        jLabel6.setText("Tên Danh Mục");

        jLabel7.setText("Mô Tả");

        jLabel8.setText("Trạng Thái");

        txtMASP.setEditable(false);

        cbTRANGTHAI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnXOA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/Delete.png"))); // NOI18N
        btnXOA.setText("Xóa");
        btnXOA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXOAActionPerformed(evt);
            }
        });

        btnSUA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/Gear.png"))); // NOI18N
        btnSUA.setText("Sửa");
        btnSUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSUAActionPerformed(evt);
            }
        });

        btnTHEM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/Add.png"))); // NOI18N
        btnTHEM.setText("Thêm");
        btnTHEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTHEMActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel9.setText("QUẢN LÝ SẢN PHẨM");

        cbTENDM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbTENDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTENDMActionPerformed(evt);
            }
        });

        cbTENTH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnDANHMUC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/Add.png"))); // NOI18N
        btnDANHMUC.setText("Thêm Danh Mục");
        btnDANHMUC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDANHMUCActionPerformed(evt);
            }
        });

        btnTHUONGHIEU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/Add.png"))); // NOI18N
        btnTHUONGHIEU.setText("Thêm Thương Hiệu");
        btnTHUONGHIEU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTHUONGHIEUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTENSP, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMASP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(cbTENDM, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbTENTH, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSOLUONG)
                            .addComponent(txtMOTA)
                            .addComponent(txtGIA)
                            .addComponent(cbTRANGTHAI, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(219, 219, 219))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTHUONGHIEU)
                        .addGap(18, 18, 18)
                        .addComponent(btnDANHMUC)
                        .addGap(18, 18, 18)
                        .addComponent(btnTHEM)
                        .addGap(18, 18, 18)
                        .addComponent(btnSUA)
                        .addGap(18, 18, 18)
                        .addComponent(btnXOA)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtGIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtMASP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(cbTENDM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtSOLUONG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(cbTRANGTHAI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbTENTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTENSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtMOTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXOA)
                    .addComponent(btnSUA)
                    .addComponent(btnTHEM)
                    .addComponent(btnDANHMUC)
                    .addComponent(btnTHUONGHIEU))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTHEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTHEMActionPerformed
        // TODO add your handling code here:
        if(rowSP == -1){
            JOptionPane.showMessageDialog(this, "Bạn phải chọn một dòng dữ liệu trong bảng để thêm");
        } else {
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm sản phẩm này không?");
            if(confirm == JOptionPane.YES_OPTION){
                spdao.insertSP(this.getSP());
                this.fillTB();
                JOptionPane.showMessageDialog(this, "Thêm thành công!");
            }
        }
    }//GEN-LAST:event_btnTHEMActionPerformed

    private void btnSUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSUAActionPerformed
        // TODO add your handling code here:
        if(rowSP != -1){
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa sản phẩm này không?");
            if(confirm == JOptionPane.YES_OPTION){
                spdao.updateSP(this.getSP());
                this.fillTB();
                JOptionPane.showMessageDialog(this, "Sửa thành công!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn một dòng dữ liệu trong bảng để sửa");
        }
    }//GEN-LAST:event_btnSUAActionPerformed

    private void btnXOAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXOAActionPerformed
        // TODO add your handling code here:
        if(rowSP == -1){
            JOptionPane.showMessageDialog(this, "Bạn phải chọn một dòng dữ liệu trong bảng để xóa");
        } else {
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa sản phẩm này không?");
            if(confirm == JOptionPane.YES_OPTION){
                int sr = tblSANPHAM.getSelectedRow();
                int maSP = Integer.parseInt(tblSANPHAM.getValueAt(sr, 0).toString());
                spdao.deleteSP(maSP);
                txtMASP.setText(" ");
                txtGIA.setText(" ");
                txtMOTA.setText(" ");
                txtSOLUONG.setText(" ");
                txtTENSP.setText(" ");
                this.fillTB();
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
            }
        }
    }//GEN-LAST:event_btnXOAActionPerformed

    private void btnTHUONGHIEUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTHUONGHIEUActionPerformed
        // TODO add your handling code here:
        HomeJFrame homeFrame = new HomeJFrame(1);
        QuanLyThuongHieuJFrame QLTHFrame = new QuanLyThuongHieuJFrame(homeFrame, "QLSP");
        QLTHFrame.setLocationRelativeTo(null);
        QLTHFrame.setVisible(true); 
    }//GEN-LAST:event_btnTHUONGHIEUActionPerformed

    private void btnDANHMUCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDANHMUCActionPerformed
        // TODO add your handling code here:
        HomeJFrame homeFrame = new HomeJFrame(1);
        QuanLyDanhMucJFrame QLDMFrame = new QuanLyDanhMucJFrame(homeFrame, "QLSP");
        QLDMFrame.setLocationRelativeTo(null);
        QLDMFrame.setVisible(true); 
    }//GEN-LAST:event_btnDANHMUCActionPerformed

    private void tblSANPHAMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSANPHAMMouseClicked
        // TODO add your handling code here:
        rowSP = tblSANPHAM.getSelectedRow();

        txtMASP.setText(tblSANPHAM.getValueAt(rowSP, 0).toString());
        cbTENDM.setSelectedItem(tblSANPHAM.getValueAt(rowSP, 1).toString());
        cbTENTH.setSelectedItem(tblSANPHAM.getValueAt(rowSP, 2).toString());
        txtTENSP.setText(tblSANPHAM.getValueAt(rowSP, 3).toString());
        txtGIA.setText(tblSANPHAM.getValueAt(rowSP, 4).toString());
        txtSOLUONG.setText(tblSANPHAM.getValueAt(rowSP, 5).toString());
        cbTRANGTHAI.setSelectedItem(tblSANPHAM.getValueAt(rowSP, 6).toString());
        txtMOTA.setText(tblSANPHAM.getValueAt(rowSP, 7).toString());
    }//GEN-LAST:event_tblSANPHAMMouseClicked

    private void cbTENDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTENDMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTENDMActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDANHMUC;
    private javax.swing.JButton btnSUA;
    private javax.swing.JButton btnTHEM;
    private javax.swing.JButton btnTHUONGHIEU;
    private javax.swing.JButton btnXOA;
    private javax.swing.JComboBox<String> cbTENDM;
    private javax.swing.JComboBox<String> cbTENTH;
    private javax.swing.JComboBox<String> cbTRANGTHAI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSANPHAM;
    private javax.swing.JTextField txtGIA;
    private javax.swing.JTextField txtMASP;
    private javax.swing.JTextField txtMOTA;
    private javax.swing.JTextField txtSOLUONG;
    private javax.swing.JTextField txtTENSP;
    // End of variables declaration//GEN-END:variables
}
