/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.QLTHDAO;
import entity.QLTHENTITY;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author MSI USER
 */
public class QuanLyThuongHieuJFrame extends javax.swing.JFrame {

    private int rowTH = -1;
    private String previousPage;
    QLTHDAO thdao = new QLTHDAO();
    /**
     * Creates new form QuanLyThuongHieuJFrame
     */
    public QuanLyThuongHieuJFrame(JFrame previousFrame, String previousPage) {
        this.previousPage = previousPage;
        initComponents();
        setLocationRelativeTo(null);
        addBackButton();
        previousFrame.setVisible(false);
        fillTB();
    }
    
    private void addBackButton() {
        btnQUAYLAI.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Đóng cửa sổ hiện tại (QuanLyThuongHieuJFrame)
                dispose();

                // Nếu truy cập từ HomeJFrame
                if (previousPage.equals("Home")) {
                    HomeJFrame homeFrame = new HomeJFrame(1);  // Quay lại HomeJFrame, truyền ID 1 (Hoặc tùy theo ID bạn muốn)
                    homeFrame.setLocationRelativeTo(null);
                    homeFrame.setVisible(true);
                }
                // Nếu truy cập từ QuanLySanPhamJPanel
                else if (previousPage.equals("QLSP")) {
                    QuanLySanPhamJPanel qlspPanel = new QuanLySanPhamJPanel();
                    qlspPanel.setVisible(true);
                }
            }
        });
    }
    
    public void fillTB(){
        DefaultTableModel model = (DefaultTableModel) tblTHUONGHIEU.getModel();
        model.setRowCount(0);
        for (QLTHENTITY th : thdao.getAllTH()) {
            Object data[] = {
                th.getMaTH(),
                th.getTenTH()
            };
            model.addRow(data);
        }
        tblTHUONGHIEU.setModel(model);
    }
    
    public QLTHENTITY getTH(){
        String tenTH = txtTENTH.getText();
        
        int maTH = 0;
        if (!txtMATH.getText().isBlank()) {
            maTH = Integer.parseInt(txtMATH.getText());
        }
        
        QLTHENTITY th = new QLTHENTITY(maTH, tenTH);
        return th;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTHUONGHIEU = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnXOA = new javax.swing.JButton();
        btnSUA = new javax.swing.JButton();
        btnTHEM = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTENTH = new javax.swing.JTextField();
        txtMATH = new javax.swing.JTextField();
        btnQUAYLAI = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("QUẢN LÝ THƯƠNG HIỆU");

        tblTHUONGHIEU.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã Thương Hiệu", "Tên Thương Hiệu"
            }
        ));
        tblTHUONGHIEU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTHUONGHIEUMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTHUONGHIEU);

        btnXOA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/Delete.png"))); // NOI18N
        btnXOA.setText("Xóa");
        btnXOA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXOAActionPerformed(evt);
            }
        });

        btnSUA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/Gear.png"))); // NOI18N
        btnSUA.setText("Sửa");
        btnSUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSUAActionPerformed(evt);
            }
        });

        btnTHEM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/Add.png"))); // NOI18N
        btnTHEM.setText("Thêm");
        btnTHEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTHEMActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã Thương Hiệu");

        jLabel3.setText("Tên Thương Hiệu");

        txtMATH.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(9, 9, 9)
                        .addComponent(txtMATH))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(txtTENTH, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2))
                    .addComponent(txtMATH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3))
                    .addComponent(txtTENTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnQUAYLAI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/Left.png"))); // NOI18N
        btnQUAYLAI.setText("Quay Lại");
        btnQUAYLAI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQUAYLAIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTHEM)
                        .addGap(18, 18, 18)
                        .addComponent(btnSUA)
                        .addGap(18, 18, 18)
                        .addComponent(btnXOA))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(627, 627, 627)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(353, 353, 353)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnQUAYLAI)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(292, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnQUAYLAI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXOA)
                    .addComponent(btnSUA)
                    .addComponent(btnTHEM))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTHEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTHEMActionPerformed
        // TODO add your handling code here:
        if(rowTH == -1){
            JOptionPane.showMessageDialog(this, "Bạn phải chọn một dòng dữ liệu trong bảng để thêm");
        } else {
            int confirm = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn thêm thương hiệu này không?");
            if(confirm == JOptionPane.YES_OPTION){
                thdao.insertTH(this.getTH());
                this.fillTB();
                JOptionPane.showMessageDialog(rootPane, "Thêm thành công!");
            }
        }
    }//GEN-LAST:event_btnTHEMActionPerformed

    private void btnSUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSUAActionPerformed
        // TODO add your handling code here:
        if (rowTH != -1){
            int confirm = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn sửa thương hiệu này không?");
            if(confirm == JOptionPane.YES_OPTION){
                thdao.updateTH(this.getTH());
                this.fillTB();
                JOptionPane.showMessageDialog(rootPane, "Sửa thành công!");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Bạn phải chọn một dòng dữ liệu trong bảng để sửa");
        }
    }//GEN-LAST:event_btnSUAActionPerformed

    private void btnXOAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXOAActionPerformed
        // TODO add your handling code here:
        if(rowTH == -1){
            JOptionPane.showMessageDialog(this, "Bạn phải chọn một dòng dữ liệu trong bảng để xóa");
        } else {
            int confirm = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn xóa thương hiệu này không?");
            if(confirm == JOptionPane.YES_OPTION){
                int maTH = Integer.parseInt(txtMATH.getText());
                thdao.deleteTH(maTH);
                txtMATH.setText(" ");
                txtTENTH.setText(" ");
                this.fillTB();
                JOptionPane.showMessageDialog(rootPane, "Xóa thành công!");
            }
        }
    }//GEN-LAST:event_btnXOAActionPerformed

    private void tblTHUONGHIEUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTHUONGHIEUMouseClicked
        // TODO add your handling code here:
        rowTH = tblTHUONGHIEU.getSelectedRow();

        txtMATH.setText(tblTHUONGHIEU.getValueAt(rowTH, 0).toString());
        txtTENTH.setText(tblTHUONGHIEU.getValueAt(rowTH, 1).toString());
    }//GEN-LAST:event_tblTHUONGHIEUMouseClicked

    private void btnQUAYLAIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQUAYLAIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQUAYLAIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyThuongHieuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyThuongHieuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyThuongHieuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyThuongHieuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HomeJFrame homeFrame = new HomeJFrame(1);
                new QuanLyThuongHieuJFrame(homeFrame, "Home").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQUAYLAI;
    private javax.swing.JButton btnSUA;
    private javax.swing.JButton btnTHEM;
    private javax.swing.JButton btnXOA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTHUONGHIEU;
    private javax.swing.JTextField txtMATH;
    private javax.swing.JTextField txtTENTH;
    // End of variables declaration//GEN-END:variables
}
