/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.QLNVDAO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import entity.QLNVENTITY;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author MSI USER
 */
public class QuanLyNhanVienJPanel extends javax.swing.JPanel {

    private int rowNV = -1;
    QLNVDAO nvdao = new QLNVDAO();
    private Map<String, Integer> qmap = new HashMap<>();
    private String getKeyFromValue(Map<String, Integer> map, int value){
        for (Map.Entry<String, Integer> entry : map.entrySet()) {
            if(entry.getValue() == value){
                return entry.getKey();
            }
        }
        return null;
    }
    /**
     * Creates new form QuanLyNhanVienJPanel
     */
    public QuanLyNhanVienJPanel() {
        initComponents();
        fillCB();
        fillTable();
        tblQLNV.getColumnModel().getColumn(6).setCellRenderer(new PasswordRenderer());
    }
    
    public void fillCB(){
        qmap.put("Admin", 1);
        qmap.put("Nhân Viên", 2);
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.removeAllElements();
        for (Map.Entry<String, Integer> entry : qmap.entrySet()) {
            model.addElement(entry.getKey());
        }
        cbQUYEN.setModel(model);
    }
    
    public void fillTable(){
        DefaultTableModel model = (DefaultTableModel) tblQLNV.getModel();
        model.setRowCount(0);
        for (QLNVENTITY nv : nvdao.getAllNV()) {
            Object data[] = {
                nv.getMaNV(),
                nv.getTenNV(),
                nv.getNgaySinh().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")),
                nv.getSoDienThoai(),
                nv.getEmail(),
                nv.getDiaChi(),
                nv.getMatKhau(),
                getKeyFromValue(qmap, nv.getQuyen())
            };
            model.addRow(data);
        }
        tblQLNV.setModel(model);
    }
    
    public QLNVENTITY getNV(){
        String tenNV = txtTENNV.getText().trim();
        String sdt = txtSDT.getText().trim();
        String email = txtEMAIL.getText().trim();
        String diaChi = txtDIACHI.getText().trim();
        String matKhau = txtMATKHAU.getText().trim();
        String quyen = (String) cbQUYEN.getSelectedItem();
        int maQ = qmap.get(quyen);
        
        LocalDate ngaySinh = null;
        try {
            DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            ngaySinh = LocalDate.parse(txtNGAYSINH.getText().trim(), fmt);
        } catch (DateTimeParseException ex) {
            System.err.println("Ngày sinh không đúng định dạng!");
        }
        
        int maNV = 0;
        if (!txtMANV.getText().isBlank()) {
            maNV = Integer.parseInt(txtMANV.getText().trim());
        }
        
        QLNVENTITY nv = new QLNVENTITY(maNV, maQ, tenNV, sdt, email, diaChi, matKhau, ngaySinh);
        return nv;
    };
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTENNV = new javax.swing.JTextField();
        txtNGAYSINH = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtEMAIL = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDIACHI = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMATKHAU = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbQUYEN = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQLNV = new javax.swing.JTable();
        btnTHEM = new javax.swing.JButton();
        btnSUA = new javax.swing.JButton();
        btnXOA = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtMANV = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        jLabel1.setText("Tên Nhân Viên");

        jLabel2.setText("Ngày Sinh");

        jLabel3.setText("Số Điện Thoại");

        jLabel4.setText("Email");

        txtTENNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTENNVActionPerformed(evt);
            }
        });

        txtNGAYSINH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNGAYSINHActionPerformed(evt);
            }
        });

        jLabel5.setText("Địa Chỉ");

        jLabel6.setText("Mật Khẩu");

        jLabel7.setText("Quyền");

        cbQUYEN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblQLNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Nhân Viên", "Tên Nhân Viên", "Ngày Sinh", "Số Điện Thoại", "Email", "Địa Chỉ", "Mật Khẩu", "Quyền"
            }
        ));
        tblQLNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQLNVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblQLNV);

        btnTHEM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/Add.png"))); // NOI18N
        btnTHEM.setText("Thêm");
        btnTHEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTHEMActionPerformed(evt);
            }
        });

        btnSUA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/Gear.png"))); // NOI18N
        btnSUA.setText("Sửa");
        btnSUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSUAActionPerformed(evt);
            }
        });

        btnXOA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/Delete.png"))); // NOI18N
        btnXOA.setText("Xóa");
        btnXOA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXOAActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel8.setText("THÔNG TIN NHÂN VIÊN");

        txtMANV.setEditable(false);

        jLabel9.setText("Mã Nhân Viên");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTHEM)
                        .addGap(18, 18, 18)
                        .addComponent(btnSUA)
                        .addGap(18, 18, 18)
                        .addComponent(btnXOA))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 358, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMANV, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtSDT)
                    .addComponent(txtNGAYSINH)
                    .addComponent(txtTENNV))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(22, 22, 22)
                        .addComponent(cbQUYEN, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDIACHI, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtMATKHAU, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMANV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDIACHI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtMATKHAU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbQUYEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtTENNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNGAYSINH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTHEM)
                    .addComponent(btnSUA)
                    .addComponent(btnXOA))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTENNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTENNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTENNVActionPerformed

    private void txtNGAYSINHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNGAYSINHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNGAYSINHActionPerformed

    private void btnTHEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTHEMActionPerformed
        // TODO add your handling code here:
        if (txtTENNV.getText().trim().isEmpty() ||
            txtNGAYSINH.getText().trim().isEmpty() ||
            txtSDT.getText().trim().isEmpty() ||
            txtEMAIL.getText().trim().isEmpty() ||
            txtDIACHI.getText().trim().isEmpty() ||
            txtMATKHAU.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin nhân viên");
            return;
        }
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm nhân viên này không ?");
            if(confirm == JOptionPane.YES_OPTION){
                nvdao.insertNV(getNV());
                fillTable();
                JOptionPane.showMessageDialog(this, "Thêm thành công!");
            }
    }//GEN-LAST:event_btnTHEMActionPerformed

    private void tblQLNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQLNVMouseClicked
        // TODO add your handling code here:
        rowNV = tblQLNV.getSelectedRow();
        
        txtMANV.setText(String.valueOf(tblQLNV.getValueAt(rowNV, 0).toString()));
        txtTENNV.setText(String.valueOf(tblQLNV.getValueAt(rowNV, 1).toString()));
        txtNGAYSINH.setText(String.valueOf(tblQLNV.getValueAt(rowNV, 2).toString()));
        txtSDT.setText(String.valueOf(tblQLNV.getValueAt(rowNV, 3).toString()));
        txtEMAIL.setText(String.valueOf(tblQLNV.getValueAt(rowNV, 4).toString()));
        txtDIACHI.setText(String.valueOf(tblQLNV.getValueAt(rowNV, 5).toString()));
        txtMATKHAU.setText(String.valueOf(tblQLNV.getValueAt(rowNV, 6).toString()));
        cbQUYEN.setSelectedItem(tblQLNV.getValueAt(rowNV, 7).toString());
    }//GEN-LAST:event_tblQLNVMouseClicked

    private void btnSUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSUAActionPerformed
        // TODO add your handling code here:
        if(rowNV != -1){
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa nhân viên này không ?");
            if(confirm == JOptionPane.YES_OPTION){
                nvdao.updateNV(this.getNV());
                fillTable();
                JOptionPane.showMessageDialog(this, "Sửa thành công!");
            }
        } else{
            JOptionPane.showMessageDialog(this, "Bạn phải chọn một dòng dữ liệu trong bảng để sửa");
        }
    }//GEN-LAST:event_btnSUAActionPerformed

    private void btnXOAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXOAActionPerformed
        // TODO add your handling code here:
        if(rowNV == -1){
            JOptionPane.showMessageDialog(this, "Bạn phải chọn một dòng dữ liệu trong bảng để xóa");
        } else {
            int maQ = qmap.get(tblQLNV.getValueAt(rowNV, 7).toString());
            if(maQ == 1){
                JOptionPane.showMessageDialog(this, "Bạn không thể xóa tài khoản Admin!");
            } else {
                int confirm = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa nhân viên này không ?");
                if(confirm == JOptionPane.YES_OPTION){
                    int maNV = Integer.parseInt(txtMANV.getText().trim());
                    nvdao.deleteNV(maNV);
                    txtMATKHAU.setText(" ");
                    txtDIACHI.setText(" ");
                    txtEMAIL.setText(" ");
                    txtMANV.setText(" ");
                    txtNGAYSINH.setText(" ");
                    txtSDT.setText(" ");
                    txtTENNV.setText(" ");
                    fillTable();
                    JOptionPane.showMessageDialog(this, "Xóa thành công!");
                }
            }
        }
    }//GEN-LAST:event_btnXOAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSUA;
    private javax.swing.JButton btnTHEM;
    private javax.swing.JButton btnXOA;
    private javax.swing.JComboBox<String> cbQUYEN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblQLNV;
    private javax.swing.JTextField txtDIACHI;
    private javax.swing.JTextField txtEMAIL;
    private javax.swing.JTextField txtMANV;
    private javax.swing.JTextField txtMATKHAU;
    private javax.swing.JTextField txtNGAYSINH;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTENNV;
    // End of variables declaration//GEN-END:variables
}
