/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.QLHDDAO;
import entity.QLCTHDENTITY;
import entity.QLHDENTITY;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSI USER
 */
public class QuanLyHoaDonJPanel extends javax.swing.JPanel {

    private int rowHD = -1;
    private Map<String, Integer> hdmap = new HashMap<>();
    QLHDDAO hddao = new QLHDDAO();
    private Map<String, Integer> tthdmap = new HashMap<>();

    private String getKeyFromValue(Map<String, Integer> map, int value) {
        for (Map.Entry<String, Integer> entry : map.entrySet()) {
            if (entry.getValue() == value) {
                return entry.getKey();
            }
        }
        return null;
    }

    /**
     * Creates new form QuanLyHoaDonJPanel
     */
    public QuanLyHoaDonJPanel() {
        initComponents();
        fillTable();
    }

    public void fillTable() {
        hdmap.put("Đang Xử Lý", 0);
        hdmap.put("Đã Thanh Toán", 1);
        hdmap.put("Hủy", 2);
        DefaultTableModel model = (DefaultTableModel) tblQLHD.getModel();
        model.setRowCount(0);
        for (QLHDENTITY hoaDon : hddao.getAllHD()) {
            Object data[] = {
                hoaDon.getMaHD(),
                hoaDon.getNgayLapHD(),
                getKeyFromValue(hdmap, hoaDon.getTrangThaiHD())};
            model.addRow(data);
        }
        tblQLHD.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQLHD = new javax.swing.JTable();
        btnCT = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Quản Lý Hóa Đơn");

        tblQLHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Hóa Đơn", "Ngày Lập", "Trạng Thái"
            }
        ));
        tblQLHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQLHDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblQLHD);

        btnCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/Search.png"))); // NOI18N
        btnCT.setText("Chi Tiết");
        btnCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 341, Short.MAX_VALUE)
                        .addComponent(btnCT))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnCT))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblQLHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQLHDMouseClicked
        // TODO add your handling code here:
        rowHD = tblQLHD.getSelectedRow();
    }//GEN-LAST:event_tblQLHDMouseClicked

    private void btnCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCTActionPerformed
        // TODO add your handling code here:
        int maHD = Integer.parseInt(tblQLHD.getValueAt(rowHD, 0).toString());
        QLHDENTITY hde = hddao.getOneHD(maHD);
        int trangThai = hde.getTrangThaiHD();
        hdmap.put("Đang Xử Lý", 0);
        hdmap.put("Đã Thanh Toán", 1);
        hdmap.put("Hủy", 2);

        if (trangThai == 0 || trangThai == 2) {
            JOptionPane.showMessageDialog(this, "Hóa đơn chưa thanh toán thành công");
        } else if (trangThai == 1) {
            CTHDJFrame cthd = new CTHDJFrame(maHD);
            cthd.setLocationRelativeTo(null);
            cthd.setVisible(true);
        }
    }//GEN-LAST:event_btnCTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblQLHD;
    // End of variables declaration//GEN-END:variables
}
