/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.QLDMDAO;
import entity.QLDMENTITY;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSI USER
 */
public class QuanLyDanhMucJFrame extends javax.swing.JFrame {

    private String previousPage;
    private QLDMDAO dmdao = new QLDMDAO();
    /**
     * Creates new form QuanLyDanhHieuJFrame
     */
    public QuanLyDanhMucJFrame(JFrame previousFrame, String previousPage) {
        this.previousPage = previousPage;
        initComponents();
        setLocationRelativeTo(null);
        addBackButton();
        previousFrame.setVisible(false);
        fillTB();
    }
    
    private void addBackButton() {
        btnQUAYLAI.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Đóng cửa sổ hiện tại (QuanLyThuongHieuJFrame)
                dispose();

                // Nếu truy cập từ HomeJFrame
                if (previousPage.equals("Home")) {
                    HomeJFrame homeFrame = new HomeJFrame(1);  // Quay lại HomeJFrame, truyền ID 1 (Hoặc tùy theo ID bạn muốn)
                    homeFrame.setLocationRelativeTo(null);
                    homeFrame.setVisible(true);
                }
                // Nếu truy cập từ QuanLySanPhamJPanel
                else if (previousPage.equals("QLSP")) {
                    QuanLySanPhamJPanel qlspPanel = new QuanLySanPhamJPanel();
                    qlspPanel.setVisible(true);
                }
            }
        });
    }
    
    public void fillTB(){
        DefaultTableModel model = (DefaultTableModel) tblDANHMUC.getModel();
        model.setRowCount(0);
        for (QLDMENTITY dm : dmdao.getAllDM()) {
            Object data[] = {
                dm.getMaDM(),
                dm.getTenDM()
            };
            model.addRow(data);
        }
        tblDANHMUC.setModel(model);
    }
    
    public QLDMENTITY getDM(){
        String tenDM = txtTENDM.getText();
        
        int maDM = 0;
        if (!txtMADM.getText().isBlank()) {
            maDM = Integer.parseInt(txtMADM.getText());
        }
        
        QLDMENTITY dm = new QLDMENTITY(maDM, tenDM);
        return dm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDANHMUC = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnXOA = new javax.swing.JButton();
        btnSUA = new javax.swing.JButton();
        btnTHEM = new javax.swing.JButton();
        txtTENDM = new javax.swing.JTextField();
        txtMADM = new javax.swing.JTextField();
        btnQUAYLAI = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblDANHMUC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã Danh Mục", "Tên Danh Mục"
            }
        ));
        tblDANHMUC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDANHMUCMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDANHMUC);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel4.setText("QUẢN LÝ DANH MỤC");

        jLabel1.setText("Mã Danh Mục");

        jLabel2.setText("Tên Danh Mục");

        btnXOA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/Delete.png"))); // NOI18N
        btnXOA.setText("Xóa");
        btnXOA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXOAActionPerformed(evt);
            }
        });

        btnSUA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/Gear.png"))); // NOI18N
        btnSUA.setText("Sửa");
        btnSUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSUAActionPerformed(evt);
            }
        });

        btnTHEM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/Add.png"))); // NOI18N
        btnTHEM.setText("Thêm");
        btnTHEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTHEMActionPerformed(evt);
            }
        });

        txtMADM.setEditable(false);

        btnQUAYLAI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/Left.png"))); // NOI18N
        btnQUAYLAI.setText("Quay Lại");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(304, 304, 304)
                        .addComponent(btnQUAYLAI))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnTHEM)
                        .addGap(18, 18, 18)
                        .addComponent(btnSUA)
                        .addGap(18, 18, 18)
                        .addComponent(btnXOA)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMADM, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTENDM, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(297, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(btnQUAYLAI))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMADM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTENDM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXOA)
                    .addComponent(btnSUA)
                    .addComponent(btnTHEM))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTHEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTHEMActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn thêm danh mục này không?");
        if(confirm == JOptionPane.YES_OPTION){
            dmdao.insertDM(this.getDM());
            this.fillTB();
            JOptionPane.showMessageDialog(rootPane, "Thêm thành công!");
        }
    }//GEN-LAST:event_btnTHEMActionPerformed

    private void btnSUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSUAActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn sửa danh mục này không?");
        if(confirm == JOptionPane.YES_OPTION){
            dmdao.updateDM(this.getDM());
            this.fillTB();
            JOptionPane.showMessageDialog(rootPane, "Sửa thành công!");
        }
    }//GEN-LAST:event_btnSUAActionPerformed

    private void btnXOAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXOAActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn xóa danh mục này không?");
        if(confirm == JOptionPane.YES_OPTION){
            int maDM = Integer.parseInt(txtMADM.getText());
            dmdao.deleteDM(maDM);
            txtMADM.setText(" ");
            txtTENDM.setText(" ");
            this.fillTB();
            JOptionPane.showMessageDialog(rootPane, "Xóa thành công!");
        }
    }//GEN-LAST:event_btnXOAActionPerformed

    private void tblDANHMUCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDANHMUCMouseClicked
        // TODO add your handling code here:
        int sr = tblDANHMUC.getSelectedRow();

        if (sr >= 0) {
            txtMADM.setText(tblDANHMUC.getValueAt(sr, 0).toString());
            txtTENDM.setText(tblDANHMUC.getValueAt(sr, 1).toString());
        }
    }//GEN-LAST:event_tblDANHMUCMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyDanhMucJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyDanhMucJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyDanhMucJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyDanhMucJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HomeJFrame homeFrame = new HomeJFrame(1);
                new QuanLyDanhMucJFrame(homeFrame, "Home").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQUAYLAI;
    private javax.swing.JButton btnSUA;
    private javax.swing.JButton btnTHEM;
    private javax.swing.JButton btnXOA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDANHMUC;
    private javax.swing.JTextField txtMADM;
    private javax.swing.JTextField txtTENDM;
    // End of variables declaration//GEN-END:variables
}
